version: "3.9"
services:

  web:
    build: .
    ports:
      - "8000:5000"
    networks:
      - all

  codeprojectAI:
    image: "codeproject/ai-server"

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"