version: "3.9"
services:

  # web:
  #   build: .
  #   ports:
  #     - "8000:5000"
  #   networks:
  #     - all

  codeproject-ai:
    image: "codeproject/ai-server"
    networks:
      - all
    ports:
      - "5000:5000"

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"